version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    env_file:
    - .env

  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    depends_on:
    - tweet_collector
    env_file:
    - .env
    